name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.1

    - name: Install dependencies
      run: |
        emacs -batch --eval "(require 'package)" \
              --eval "(add-to-list 'package-archives '(\"melpa\" . \"https://melpa.org/packages/\") t)" \
              --eval "(package-initialize)" \
              --eval "(package-refresh-contents)" \
              --eval "(package-install 'magit)" \
              --eval "(package-install 'transient)" \
              --eval "(package-install 'package-lint)"

    - name: Run tests
      run: |
        emacs -batch -L . -l ert -l link-to-remote.el -l link-to-remote-test.el -f ert-run-tests-batch-and-exit

    - name: Byte compile
      run: |
        emacs -batch -L . -f batch-byte-compile link-to-remote.el

    - name: Lint package
      run: |
        emacs -batch -l package-lint -f package-lint-batch-and-exit link-to-remote.el