name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: 29.1

    - name: Test
      run: |
        echo "Running basic syntax check..."
        emacs -Q --batch -f batch-byte-compile link-to-remote.el